# Generated by Django 3.2.25 on 2024-07-10 07:48

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0003_alter_introduce_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduce',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
