# Generated by Django 3.2.25 on 2024-07-13 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pericriativity', '0006_auto_20240713_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationnote',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationnote',
            name='credits',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
