# Generated by Django 3.2.25 on 2024-07-13 17:21

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0007_auto_20240713_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationnote',
            name='note',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
