# Generated by Django 3.2.25 on 2024-07-13 17:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0009_alter_publicationnote_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationnote',
            name='publication',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
