# Generated by Django 3.2.25 on 2024-07-13 19:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0010_alter_publicationnote_publication'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicationnote',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
