# Generated by Django 3.2.25 on 2024-07-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0011_alter_publicationnote_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicationnote',
            managers=[
            ],
        ),
    ]
