# Generated by Django 3.2.25 on 2024-07-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0012_alter_publicationnote_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationnote',
            name='note_type',
            field=models.CharField(choices=[('ED', 'publicado'), ('SH', 'não publicado')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
