# Generated by Django 3.2.25 on 2024-07-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0013_publicationnote_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationnote',
            name='note_type',
            field=models.CharField(choices=[('NT', 'notas etnográficas'), ('PU', 'publicações')], max_length=2),
        ),
    ]
