# Generated by Django 3.2.25 on 2024-07-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0014_alter_publicationnote_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationnote',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
