# Generated by Django 3.2.25 on 2024-07-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0017_auto_20240714_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationnote',
            options={'ordering': ['-publish'], 'verbose_name': 'texto', 'verbose_name_plural': 'textos'},
        ),
    ]
