# Generated by Django 3.2.25 on 2024-07-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0019_alter_publicationnote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationnote',
            name='note_type',
        ),
        migrations.RemoveField(
            model_name='publicationnote',
            name='publication',
        ),
    ]
