# Generated by Django 3.2.25 on 2024-07-14 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pericriativity', '0020_auto_20240714_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationnote',
            options={'ordering': ['-publish'], 'verbose_name': 'nota etnografica', 'verbose_name_plural': 'notas etnograficas'},
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='titulo')),
                ('credits', models.CharField(max_length=250, verbose_name='autoria')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='nome da pagina')),
                ('publication', django_quill.fields.QuillField(blank=True, null=True, verbose_name='publicacao')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ED', 'publicado'), ('SH', 'não publicado')], default='SH', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autoria do post')),
            ],
            options={
                'verbose_name': 'publicacao',
                'verbose_name_plural': 'publicacoes',
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-publish'], name='pericriativ_publish_098246_idx'),
        ),
    ]
