# Generated by Django 3.2.25 on 2024-07-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0022_auto_20240714_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
    ]
