# Generated by Django 3.2.25 on 2024-07-14 21:19

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0023_remove_publication_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduce',
            options={'ordering': ['-publish'], 'verbose_name': 'home', 'verbose_name_plural': 'home'},
        ),
        migrations.RemoveField(
            model_name='introduce',
            name='slug',
        ),
        migrations.AlterField(
            model_name='introduce',
            name='body',
            field=django_quill.fields.QuillField(verbose_name='apresentação'),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='title',
            field=models.CharField(max_length=250, verbose_name='título'),
        ),
    ]
