# Generated by Django 3.2.25 on 2024-07-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0025_auto_20240714_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
