# Generated by Django 3.2.25 on 2024-07-15 20:13

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0026_delete_quillpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('event', django_quill.fields.QuillField(verbose_name='evento')),
                ('know_more', models.CharField(max_length=250, verbose_name='saiba mais')),
                ('book', models.CharField(max_length=250, verbose_name='livro de resumos')),
                ('date_event', models.DateTimeField(default=django.utils.timezone.now, help_text='Coloque a data de início do evento.', verbose_name='data do evento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
