# Generated by Django 3.2.25 on 2024-07-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0027_agenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'agenda', 'verbose_name_plural': 'agenda'},
        ),
    ]
