# Generated by Django 3.2.25 on 2024-07-15 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0028_alter_agenda_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date_event',
            field=models.DateField(default=django.utils.timezone.now, help_text='Coloque a data de início do evento.', verbose_name='data do evento'),
        ),
    ]
