# Generated by Django 3.2.25 on 2024-07-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0029_alter_agenda_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='event',
            field=models.TextField(verbose_name='evento'),
        ),
    ]
