# Generated by Django 3.2.25 on 2024-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pericriativity', '0030_alter_agenda_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='book',
            field=models.CharField(blank=True, max_length=250, verbose_name='livro de resumos'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='know_more',
            field=models.CharField(blank=True, max_length=250, verbose_name='saiba mais'),
        ),
    ]
